# Generated by Django 5.0.2 on 2024-02-28 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_ai_app', '0002_imageelement_content_imageelement_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imageelement',
            name='image',
        ),
    ]
