# Generated by Django 5.0.2 on 2024-02-28 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_ai_app', '0003_remove_imageelement_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageelement',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
    ]
