# Generated by Django 4.0 on 2024-04-15 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_ai_app', '0007_remove_imageelement_image_imageelement_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageelement',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
